-- SENTENCIA PARA CREAR USER "USUARIO" CON SU CONTRASEÑA

CREATE USER "usuario"@"localhost" IDENTIFIED WITH mysql_native_password BY "usuario123";

-- SENTENCIA PARA GENERAR PERMISO SOLO LECTURA AL USER USUARIO 

GRANT SELECT ON *.* TO "usuario"@"localhost";

-- SENTENCIA PARA CREAR EL USER ADMIN Y SU CONTRASEÑA

CREATE USER "admin"@"localhost" IDENTIFIED WITH mysql_native_password BY "admin123";

-- SENTENCIA PARA GENERAR PERMISO AL USER ADMIN DE LEER, INSERTAR Y MODIFICAR

GRANT SELECT,INSERT, UPDATE ON *.* TO "admin"@"localhost";